server:
  port: 8080

vaadin:
  launch-browser: true

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: PBM Gids
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: ${SHOW_SQL}
    database-platform: ${HIBERNATE_DIALECT:org.hibernate.dialect.HSQLDialect}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:none}
    # properties:
    #   jakarta.persistence.schema-generation.create-source: metadata
    #   jakarta.persistence.schema-generation.scripts.action: update
    #   jakarta.persistence.schema-generation.scripts.create-target: create.sql
  datasource:
    url: ${DB_URL:jdbc:hsqldb:file:./target/testdb;shutdown=true}
    driver-class-name: ${DB_DRIVER:org.hsqldb.jdbcDriver}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000 # 10 minutes
      connection-timeout: 30000 # 30 seconds
      max-lifetime: 1800000 # 30 minutes
  ldap:
    urls: ${LDAP_URL:ldap://oxideworld.local:389}
    base: ${LDAP_BASE_DN:OU=Zwijndrecht,DC=OXIDEWORLD,DC=LOCAL}
    username: ${LDAPQUERY_USER:nada} # LDAP username for authentication
    password: ${LDAPQUERY_PSW:noppes}
    filter: ${LDAPQUERY_FILTER:(sAMAccountName=%s)} # LDAP filter for searching users

##Set all logging for LDAP to DEBUG
logging:
  level:
    org:
      springframework:
        security: ERROR

under_construction_notif: ${UNDER_CONSTRUCTION_NOTIF:enabled}
under_construction_notif.msg: ${UNDER_CONSTRUCTION_NOTIF_MSG:This application is under construction. Please check back later.}
initialUsersInDev: ${INITIAL_USERS_IN_DEV:avbogget,avblocal}
